[package]
name = "vrchat_osc_input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rosc = "~0.7"
async-std = "1.11.0"
eframe = "0.17.0"
