name: CI

on: [push, pull_request]

jobs:
  build:
    name: Rust ${{ matrix.os }} ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        rust:
          - stable
        os: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true

    - uses: Swatinem/rust-cache@v1

    - name: Build
      run: cargo build
